import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import pfp from "../public/lensa.jpg";
import logo from "../public/logo.png";
import poster from "../public/poster.jpg";
import apps from "../public/apps.png";
import code from "../public/code.png";
import design from "../public/design.png";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>danialnbl Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between flex-col items-end">
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl text-black dark:text-white md:text-xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 pt-0">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Danial Nabil
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-black dark:text-white">
              Programmer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              ダニエル・Hi! I&apos;m a student at University Malaysia Pahang.
              Currently taking Bachelor of Computer Science (Software
              Engineering).
            </p>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <a href="https://twitter.com/danialnbl">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/mohamad-danial-nabil-mohamad-yusof-0735861bb">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/danialnbl">
                <AiFillGithub />
              </a>
            </div>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-10 overflow-hidden">
              <Image src={pfp} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-black">
              Services I offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching for universities student.
            </p>
          </div>
          <div className="lg:flex gap-20">
            <div className="flex flex-col justify-center items-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pb-2 text-black dark:text-white">
                Beautiful Designs
              </h3>
              <p className="py-2 text-black dark:text-white">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-teal-400">
                Design Tools I Use
              </h4>
              <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-white">Figma</p>
              <p className="text-gray-800 py-1 dark:text-white">Indesign</p>
            </div>
            <div className="flex flex-col justify-center items-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pb-2  text-black dark:text-white">
                Code your dream project
              </h3>
              <p className="py-2 text-black dark:text-white">
                Do you have an idea for your next great website or application?
                Let&apos;s make it a reality.
              </p>

              <h4 className="py-4 text-teal-600 dark:text-teal-400">
                Language I Know
              </h4>
              <p className="text-gray-800 py-1 dark:text-white">C</p>
              <p className="text-gray-800 py-1 dark:text-white">.Net</p>
              <p className="text-gray-800 py-1 dark:text-white">Typescript</p>
              <p className="text-gray-800 py-1 dark:text-white">Javascript</p>
              <p className="text-gray-800 py-1 dark:text-white">Java</p>
              <p className="text-gray-800 py-1 dark:text-white">C#</p>
              <p className="text-gray-800 py-1 dark:text-white">
                HTML, CSS, PHP
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 text-black dark:text-white">
              Portfolio
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching for universities student.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
